Implemented double click/tap scene movement, fixed UI click-through.
fixed: navigation arrows no longer allow for selection through them.
implemented: double-click or double-tap (both supported, tested) to move
from highlighted sector star to stellar system view.

still no code in place to move from system to sector view smoothly
besides spacebar.
preliminary testing showing errors when returning to sector view from
system. Affects Left/Right movement, up/down is fine. this may need to
be handled in Start() - currently empty for now.

--- Errors ---
IndexOutOfRangeException: Array index is out of
range.
Completed.GameManager.ShiftRight () (at
Assets/Scripts/GameManager.cs:238)
Completed.GameManager.Update () (at
Assets/Scripts/GameManager.cs:106)

IndexOutOfRangeException: Array index is out of
range.
Completed.GameManager.ShiftLeft () (at
Assets/Scripts/GameManager.cs:255)
Completed.GameManager.Update () (at
Assets/Scripts/GameManager.cs:98)