WIP: only send ships to discovered stars (doesn't work if prior save data already exists)
WIP - only works with first-time user (no prior save data). If there is
prior save data, then throws null reference exception because the saved
gameobjects don't exist.

NullReferenceException: Object reference not set to an instance of an
object
Star.Start () (at Assets/Scripts/Spaceobjects/Star.cs:51)